export const people = [
  {
    name: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    date: "2024-07-12",
  },
  {
    name: "Jane",
    lastName: "Doe",
    email: "jane.doe@example.com",
    date: "2024-07-13",
  },
  {
    name: "Jim",
    lastName: "Smith",
    email: "jim.smith@example.com",
    date: "2024-07-14",
  },
  {
    name: "Jill",
    lastName: "Johnson",
    email: "jill.johnson@example.com",
    date: "2024-07-15",
  },
  {
    name: "Jack",
    lastName: "Brown",
    email: "jack.brown@example.com",
    date: "2024-07-16",
  },
  {
    name: "Jenny",
    lastName: "Davis",
    email: "jenny.davis@example.com",
    date: "2024-07-17",
  },
  {
    name: "Jerry",
    lastName: "Miller",
    email: "jerry.miller@example.com",
    date: "2024-07-18",
  },
  {
    name: "Julia",
    lastName: "Wilson",
    email: "julia.wilson@example.com",
    date: "2024-07-19",
  },
  {
    name: "Joe",
    lastName: "Taylor",
    email: "joe.taylor@example.com",
    date: "2024-07-20",
  },
  {
    name: "Jessica",
    lastName: "Anderson",
    email: "jessica.anderson@example.com",
    date: "2024-07-21",
  },
  {
    name: "Jason",
    lastName: "Thomas",
    email: "jason.thomas@example.com",
    date: "2024-07-22",
  },
  {
    name: "Jennifer",
    lastName: "Moore",
    email: "jennifer.moore@example.com",
    date: "2024-07-23",
  },
  {
    name: "Jeremy",
    lastName: "Jackson",
    email: "jeremy.jackson@example.com",
    date: "2024-07-24",
  },
  {
    name: "Joanna",
    lastName: "White",
    email: "joanna.white@example.com",
    date: "2024-07-25",
  },
  {
    name: "Jonathan",
    lastName: "King",
    email: "jonathan.king@example.com",
    date: "2024-07-26",
  },
  {
    name: "Joyce",
    lastName: "Lee",
    email: "joyce.lee@example.com",
    date: "2024-07-27",
  },
  {
    name: "Joshua",
    lastName: "Lewis",
    email: "joshua.lewis@example.com",
    date: "2024-07-28",
  },
  {
    name: "Julie",
    lastName: "Roberts",
    email: "julie.roberts@example.com",
    date: "2024-07-29",
  },
  {
    name: "Justin",
    lastName: "Clark",
    email: "justin.clark@example.com",
    date: "2024-07-30",
  },
  {
    name: "Kathy",
    lastName: "Scott",
    email: "kathy.scott@example.com",
    date: "2024-07-31",
  },
  {
    name: "Kevin",
    lastName: "Campbell",
    email: "kevin.campbell@example.com",
    date: "2024-08-01",
  },
  {
    name: "Kimberly",
    lastName: "Mitchell",
    email: "kimberly.mitchell@example.com",
    date: "2024-08-02",
  },
  {
    name: "Kyle",
    lastName: "Carter",
    email: "kyle.carter@example.com",
    date: "2024-08-03",
  },
];
